### ISSUE TITLE
Just Now is about a minute or more an inconsistence 

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#105]
<img width="527" alt="screen shot 2015-08-12 at 17 17 47" src="https://cloud.githubusercontent.com/assets/880960/9227933/5c7f412c-4116-11e5-94c0-c1995c80ba27.png">

<img width="542" alt="screen shot 2015-08-12 at 17 18 30" src="https://cloud.githubusercontent.com/assets/880960/9227943/661da05c-4116-11e5-98e0-f3c848391120.png">

**Comment by zGrav** [comment]
fixed, otherwise reopen
