### ISSUE TITLE
user online status broken

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#112]
reported by `@flame` on `FF40 / Windows 10`

<img width="151" alt="1167207d06f8ca0017295cb11069e36d" src="https://cloud.githubusercontent.com/assets/3743052/9229301/b79e9502-411c-11e5-97e6-974cb513ad32.png">
<img width="143" alt="533a8c63d0fc72d0c5d30e9fb50af0ae" src="https://cloud.githubusercontent.com/assets/3743052/9229302/b79ef6aa-411c-11e5-8ba2-ab7b19ad1017.png">

**Comment by arnehorn** [comment]
bump

**Comment by felixam** [comment]
seems to be fine for me
#273 remains though
