### ISSUE TITLE
users sometimes permantly leave dm channels

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#117]
then you cannot send that user any direct messages anymore

**Comment by felixam** [comment]
@maddrag0n kannst du das reproduzieren? Ist es vielleichgt sogar gefixt?

**Comment by maddrag0n** [comment]
@felixam when I open a dm channel to `@arne` I can see the history between the two of us, but I am the only member in the channel user list. he also does not receive anything I write.

**Comment by felixam** [comment]
/leave command still did a hard channel leave, instead of client-side hide. Fixed. behaviour will be deprecated soon when we implement this properly server-side

**Comment by maddrag0n** [comment]
does that fix users/channels that are currently broken?

**Comment by zGrav** [comment]
fixed, otherwise reopen
