### ISSUE TITLE
Web mobile - dead end

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#125]
After login there is the login screen forever. Title of the page is 'undefined ' there something written in the screen like 'this.props.title'

**Comment by arnehorn** [comment]
This the url I was reffered to - maybe it helps:

https://be.go.su/channel/5db4270e-e40f-4063-a98a-fd571f11935d

**Comment by arnehorn** [comment]
Reload doesn't help. Just if I go to be.go.su again I am logged in and it works

**Comment by DanielHeckrath** [comment]
Should be fixed in the next release
