### ISSUE TITLE
Web app loading time long

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#126]
The loading time for a site takes very very long, don't if it loads completely ever. The profile pics doesn't  show up. Chat work, channel switch as well.

**Comment by maddrag0n** [comment]
@arnehorn on desktop or on mobile devices? what internet connection?

**Comment by arnehorn** [comment]
On mobile. Wifi

**Comment by DanielHeckrath** [comment]
This should be less of an issue by the recent addition of mobile apps. Reopen if this is still a major issue.
