### ISSUE TITLE
New Message Indicator broken on Web App

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#129]

**Comment by maddrag0n** [comment]
@arnehorn please elaborate

**Comment by arnehorn** [comment]
thx @maddrag0n for the hinweising on issue reporting guidelines :)

regarding the issue: I just get randomly New Message Indicator - sometimes I get it in channels like #members but in not that crowded channels I don't get them every time

**Comment by maddrag0n** [comment]
duplicate of https://github.com/be-gosu/issues/issues/94

**Comment by arnehorn** [comment]
k
