### ISSUE TITLE
hibernation issues

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#136]
- People list in the channel are missing after hibernation

<img width="904" alt="4fd9fc01233a2064444bc57a5be0b6e9" src="https://cloud.githubusercontent.com/assets/880960/9367747/a54cc0ba-46bf-11e5-8a07-d8dc3282d2af.png">

**Comment by maddrag0n** [comment]
also past messages are not shown

**Comment by DanielHeckrath** [comment]
Messages and users are reloaded after WS reconnect. Should no longer be an issue.
