### ISSUE TITLE
Crash in join a specific #member channel iOS App

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#146]

**Comment by maddrag0n** [comment]
@arnehorn I cannot even get a teams list. how did you join a `#members` channel in-app that you are not already in?

**Comment by arnehorn** [comment]
It is a #members channel I am already in. It is in the channel list in the sidemnue

**Comment by arnehorn** [comment]
it is the 4friends #members channel t be precise

**Comment by bkuss** [comment]
probably fixed
