### ISSUE TITLE
Overlap on long named channels and other

### ISSUE THREAD

**Issue by ElinMasterRace** [be-gosu/issues#158]
Android using google chrome (Using galaxy s5)
The little green circle overlaps with The "Online" text (On any channel)
If the channel name is to long it gets brought out of format. While, i would think, it should just lower the font size and stay in position 

>I dont know if im supposed to report browser problems as well if its on a phone<
 
Screenshots showing both~

![screenshot_2015-08-25-22-37-29](https://cloud.githubusercontent.com/assets/13963058/9482625/40974664-4b96-11e5-8326-2d863506f9d2.png)
![screenshot_2015-08-25-22-41-43](https://cloud.githubusercontent.com/assets/13963058/9482626/40999f36-4b96-11e5-8e28-f146c9b1a5d3.png)

**Comment by maddrag0n** [comment]
ty for reporting!

**Comment by maddrag0n** [comment]
mostly fixed in next release. remaining enhancement as new issue here: https://github.com/be-gosu/issues/issues/159
