### ISSUE TITLE
no icon to show if a channel is private/ invisible

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#161]
it is not visible in the channel list nor in the MyTeams Section.

Maybe do a 'my Teams section at the top of teams list section? Just an idea - don't know what is a good solution.

**Comment by maddrag0n** [comment]
- we should add the lock icon in front of private channels

**Comment by maddrag0n** [comment]
show lock icon in front of private channels

**Comment by zGrav** [comment]
implemented
