### ISSUE TITLE
Create channel only private (not visible)

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#166]

**Comment by maddrag0n** [comment]
@arnehorn please explain

**Comment by arnehorn** [comment]
- I can 'create team channel' here I don't have a clue if it is private or public
- when I click on it I can enter a name - still no differentiation (check box or something) IF it is public or private nor can I decide if this channel should be pub or private
- after creating a channel I still have no idea if this channel is public or private. The _only_ way to know for sure is to enter the team list and see the icon

**Comment by maddrag0n** [comment]
this issue is partly a duplicate of https://github.com/be-gosu/issues/issues/161
for the other part there is a new issue https://github.com/be-gosu/issues/issues/176
