### ISSUE TITLE
listview image recycling bug

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#208]
reported by `@Stamiii`
> Croven appears with maddrag0n's avatar
> It not restricted to Croven or maddrag0n, and eventually everyone gets their avatar right.

![](https://maple-gosu.s3.amazonaws.com/d204b88d-f08c-4bf3-87c8-e350213a2a9f)

**Comment by felixam** [comment]
pretty sure it is fixed. Has not happened to me for quite a while at least
