### ISSUE TITLE
cannot write messages after connection loss and reconnect

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#228]
with iPhone on WiFi, after restarting my wan router, the app recovered and loaded new channel messages after a while, but would simply discard all messages that I wrote. had to force close and re-open the app to get rid of that.

**Comment by bkuss** [comment]
Do you know if your status (in the channels drawer) was showing as online or offline when it happened?

**Comment by maddrag0n** [comment]
sry. unfortunately I did not check my online status. no connecting banner in navbar tho.

**Comment by bkuss** [comment]
the code for sending messages has been rewritten. should not happen anymore.
