### ISSUE TITLE
chat user store changes cause blocking loading indicator on every odd channel switch

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#229]
develop branch

- initial channel loads fine
- first channel switch shows blocking loading indicator on chat
- second channel switch loads fine
- third channel switch shows blocking loading indicator on chat
- fourth channel switch loads fine
- …

**Comment by DanielHeckrath** [comment]
Every channel should show a blocking loading indicator on first entry within a session. Every consecutive entry should not trigger a blocking loading indicator. This behaviour is reset when the websocket loses its connection.
