### ISSUE TITLE
push notification frequency and multi-client awareness issues

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#236]
- when I am in a high frequency channel (e. g. active direct message channel), I get notifications for every single message resulting in my colleagues complaining about my phone buzzing every couple of minutes
- when I am actively writing in web client and see those messages, I still get those notifications on my smartphone
- after I have read those messages, notifications are not deleted

**Comment by felixam** [comment]
1 and 2 are fixed (rollout pending)
created #274 for point 3
