### ISSUE TITLE
Cannot delete channel due to bug

### ISSUE THREAD

**Issue by rlaniado24** [be-gosu/issues#255]
BUG- if you make a channel topic too long, you can do longer delete, leave it, or even change it, so it is stuck forever

I now have a channel stuck forever and it killing me ;-; 

Thanks,
-Ron

**Comment by felixam** [comment]
@rlaniado24 Thank you for reporting, will fix! You can also change the thannel topic via the "edit channel" action, btw. :)

**Comment by zGrav** [comment]
fixed
