### ISSUE TITLE
wtf is a potwhale?

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#26]
is this like a 🐳 smoking fucking weed? or did you mean `sperm whale`? [check it out on wiki](https://en.wikipedia.org/wiki/Sperm_whale)

we might wanna go with `blue whale` instead… why? [because](https://en.wikipedia.org/wiki/Blue_whale_penis)

**Comment by maddrag0n** [comment]
`/slap %user` should be `/me slaps %user around with an enormous blue whale 🐳.`

**Comment by OliverSonntag** [comment]
fix at comment: 3c25046352985d2271cd018a5a10827283b0345c
