### ISSUE TITLE
X-Cache REST improvement

### ISSUE THREAD

**Issue by zGrav** [be-gosu/issues#271]
Description: Many images in the application are loaded through CloudFront. However, none of the images are cache-hits in CloudFront (see X-Cache header in https://i.shikashi.me/OZW6o ) The URL itself for this particular resource looks extremely non-RESTful (as it contains an S3 bucket URL at the end of it)
￼
Suggestion: By making these resources static (as they should be), CloudFront can serve its purpose and cache the resources and thereby improve application performance significantly.

**Comment by felixam** [comment]
@zGrav Those images are actually processed by a general purpose image resizing service (hence the strange url)
But for me most of them are hits from cloudfront. 
They are not if
- you are the first one to request them
- or the image origin has set headers to no-cache
I could configure it to enforce a minimum max-age to "fix" the latter...

**Comment by zGrav** [comment]
Well, the images used in this test, at the time, were the first display of such, so maybe that's why it came back as miss.

Taking that into account, I guess this issue can be closed seeing that everything is okay.
