### ISSUE TITLE
web client regular connection losses after seemingly random time span (only happened in channel so far)

### ISSUE THREAD

**Issue by maddrag0n** [be-gosu/issues#4]

**Comment by DanielHeckrath** [comment]
Is this still an issue with the latest client side ping and connection health checking?

**Comment by maddrag0n** [comment]
issue should be renamed to “when client loses connection, only navbar is shown without further explanation”

**Comment by DanielHeckrath** [comment]
This happened when a regular profile reload failed. The new behaviour is to ignore those errors as long as the initial load succeeded.
