### ISSUE TITLE
Automatic login not working on Edge/IE

### ISSUE THREAD

**Issue by DanielHeckrath** [be-gosu/issues#74]
Check wether or not local storage and deflate is working properly on ie/edge.

**Comment by maddrag0n** [comment]
local storage seemed to be an issue on Win 8 / IE 10 as well

**Comment by DanielHeckrath** [comment]
According to [StackOverflow](http://stackoverflow.com/questions/11170716/are-there-any-characters-that-are-not-allowed-in-localstorage) IE has a problem storing certain characters in local storage. This is a bug that exists since IE8.

As a workaround, I'm currently encoding the deflated values with Base64 before storing them, but we may want to monitor the performance overhead were taking.
While were having a size gain with deflate&base64 encoding for large messages, it might be preferable to just store the values directly as long as we're not close to the size limit of the browser local storage.
