### ISSUE TITLE
Msg from maddragon was marked as soon

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#81]
A Message from mad was marked as soon - and then switched to 'just now' a little while later
From Nizz as well Screenshot att
<img width="485" alt="screen shot 2015-08-11 at 13 24 32" src="https://cloud.githubusercontent.com/assets/880960/9196527/71f0b5f8-402c-11e5-9d41-34dd9be56f2a.png">

**Comment by maddrag0n** [comment]
@arnehorn that is because I am from the future…

**Comment by maddrag0n** [comment]
most likely happens because the client time and server time are slightly out of sync. as an easy first workaround, shifting server time into the past should work

**Comment by arnehorn** [comment]
thx guy from the future! :)

**Comment by DanielHeckrath** [comment]
This might be fixed in our current dev build. Please monitor on live after rollout.
