### ISSUE TITLE
Create Team is dead end

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#85]
There is no option to get back out of 'create team' X or something

**Comment by maddrag0n** [comment]
simply hit the back button?

create team should be modal tho

**Comment by arnehorn** [comment]
Or put a X in there :)

**Comment by maddrag0n** [comment]
there is nothing underlying… so you’d end up with a blank screen LOL

**Comment by zGrav** [comment]
fixed, otherwise reopen
