### ISSUE TITLE
leave PM channel deletes History

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#86]
When I leave the PM Channel with Jan the history is gone. Jan has two PM channel with me and joins the older one.

He changed his nick at some point - maybe this issue is a result of that ... just guessing ...

**Comment by felixam** [comment]
@arnehorn please test again (on staging or be.go.su)

**Comment by arnehorn** [comment]
tested - msg history gets deleted (staging)

**Comment by arnehorn** [comment]
+ on live the same

**Comment by felixam** [comment]
solved for now (/leave command was hard leaving the channel, instead of hiding it)
